### ISSUE TITLE
Kernel methods documentation

### ISSUE THREAD

**Issue by Abubakar26** [naotoo1/prosemble#13]
Can you add proper documentation for the kernel methods would be great

**Comment by naotoo1** [comment]
The significance of kernel based methods entails  an arbitrary non-linear mapping from the input feature space to the kernel space which could possibly be of infinite dimensionality.  So with kernel methods the input data can be implicitly  mapped into a higher dimensional feature space where non-linear patterns now appear linear.

**Comment by Abubakar26** [comment]
I understood it would be nice to add these introductory lines in readme.md for beginners would be nicer but anyways its perfect
